# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00135ce637dd13fd351cba209be5c7d9c819eed9f561cf25038596fdf9b95dbd50912d84031b6c157208a3caacf75a2243dca48a3bfe1ae144eefdf296d652dd
  github_key: accba9f55d2861778603
  github_secret: fc2efc88fd6c6640974296fbf35a046390af9e2e

test:
  secret_key_base: fd3a69db23f8b1cea8f0e2b08d03ae1a8d35d9fb49d41b500eb4badfe42e2a7f14115826d972129dbfa6c053556e26140083f1122cfb18b6082b6510db2635c7
  github_key: fc2efc88fd6c6640974296fbf35a046390af9e2e
  github_secret: fc2efc88fd6c6640974296fbf35a046390af9e2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_key: <%= ENV["GITHUB_KEY"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>
